export const THEME_PRESETS = {
    classic: {
        name: 'Classic',
        description: 'Clean cream & navy',
        light: {
            bg: '#F8F7F2',
            surface: '#FFFFFF',
            surface2: '#F0EEE6',
            border: '#E2E0D6',
            border2: '#D1CFC4',
            ink: '#1A1A2E',
            ink2: '#3D3D56',
            ink3: '#7A7A8E',
            ink4: '#AEAEB8',
            red: '#E03E3E',
            orange: '#D97706',
            green: '#16A34A',
            blue: '#2563EB',
            purple: '#7C3AED',
            accent: '#1A1A2E',
        },
        dark: {
            bg: '#111118',
            surface: '#1C1C26',
            surface2: '#26263A',
            border: '#2E2E42',
            border2: '#3A3A52',
            ink: '#EEEEF2',
            ink2: '#C8C8D4',
            ink3: '#8888A0',
            ink4: '#55556A',
            red: '#F87171',
            orange: '#FBBF24',
            green: '#4ADE80',
            blue: '#60A5FA',
            purple: '#A78BFA',
            accent: '#EEEEF2',
        },
    },
    ocean: {
        name: 'Ocean',
        description: 'Deep blue & teal',
        light: {
            bg: '#F5F8FC',
            surface: '#FFFFFF',
            surface2: '#EBF2FA',
            border: '#D6E2F0',
            border2: '#C2D4E8',
            ink: '#1A2F4A',
            ink2: '#3B5576',
            ink3: '#6B8DB5',
            ink4: '#A0BFD9',
            red: '#DC2626',
            orange: '#EA580C',
            green: '#16A34A',
            blue: '#2563EB',
            purple: '#7C3AED',
            accent: '#0EA5E9',
        },
        dark: {
            bg: '#0C1929',
            surface: '#142338',
            surface2: '#1C3150',
            border: '#243D5E',
            border2: '#2E4D72',
            ink: '#E0EDFF',
            ink2: '#BAD4F5',
            ink3: '#7BA3D0',
            ink4: '#4A6F9A',
            red: '#F87171',
            orange: '#FB923C',
            green: '#4ADE80',
            blue: '#60A5FA',
            purple: '#A78BFA',
            accent: '#38BDF8',
        },
    },
    forest: {
        name: 'Forest',
        description: 'Earthy greens',
        light: {
            bg: '#F5FAF6',
            surface: '#FFFFFF',
            surface2: '#E8F5EB',
            border: '#D0E6D5',
            border2: '#B8D6BF',
            ink: '#1A3D2B',
            ink2: '#2D5A3E',
            ink3: '#5C8A6E',
            ink4: '#93B8A2',
            red: '#DC2626',
            orange: '#EA580C',
            green: '#16A34A',
            blue: '#0D9488',
            purple: '#7C3AED',
            accent: '#16A34A',
        },
        dark: {
            bg: '#0A1F13',
            surface: '#122B1C',
            surface2: '#1A3D2B',
            border: '#224A34',
            border2: '#2C5A42',
            ink: '#E0FFF0',
            ink2: '#B8E6CA',
            ink3: '#7BBF95',
            ink4: '#4A8A64',
            red: '#F87171',
            orange: '#FB923C',
            green: '#4ADE80',
            blue: '#2DD4BF',
            purple: '#A78BFA',
            accent: '#34D399',
        },
    },
    sunset: {
        name: 'Sunset',
        description: 'Warm orange & coral',
        light: {
            bg: '#FDFAF5',
            surface: '#FFFFFF',
            surface2: '#FFF0E0',
            border: '#EDDCCA',
            border2: '#DCC8B0',
            ink: '#4A2C0F',
            ink2: '#6B4422',
            ink3: '#A0724A',
            ink4: '#C49870',
            red: '#DC2626',
            orange: '#EA580C',
            green: '#16A34A',
            blue: '#2563EB',
            purple: '#7C3AED',
            accent: '#EA580C',
        },
        dark: {
            bg: '#1C0F05',
            surface: '#2A1A0D',
            surface2: '#3D2514',
            border: '#4D3320',
            border2: '#5E4030',
            ink: '#FFF1E0',
            ink2: '#FDDCB5',
            ink3: '#D4A373',
            ink4: '#A0724A',
            red: '#F87171',
            orange: '#FB923C',
            green: '#4ADE80',
            blue: '#60A5FA',
            purple: '#A78BFA',
            accent: '#FB923C',
        },
    },
    midnight: {
        name: 'Midnight',
        description: 'Purple & indigo',
        light: {
            bg: '#F8F6FD',
            surface: '#FFFFFF',
            surface2: '#EFEBFA',
            border: '#DDD5F0',
            border2: '#C8BDE6',
            ink: '#2D1B5E',
            ink2: '#4A3580',
            ink3: '#7E5FC0',
            ink4: '#A78BDA',
            red: '#DC2626',
            orange: '#EA580C',
            green: '#16A34A',
            blue: '#6366F1',
            purple: '#7C3AED',
            accent: '#7C3AED',
        },
        dark: {
            bg: '#0F0A1F',
            surface: '#1A1230',
            surface2: '#251B45',
            border: '#302352',
            border2: '#3D2E65',
            ink: '#EDE9FF',
            ink2: '#C4B5FD',
            ink3: '#8B7BBF',
            ink4: '#5A4D8A',
            red: '#F87171',
            orange: '#FB923C',
            green: '#4ADE80',
            blue: '#818CF8',
            purple: '#A78BFA',
            accent: '#8B5CF6',
        },
    },
    rose: {
        name: 'Rose',
        description: 'Pink & rose gold',
        light: {
            bg: '#FDF6F7',
            surface: '#FFFFFF',
            surface2: '#FCEAEC',
            border: '#F0D4D8',
            border2: '#E4BBC2',
            ink: '#5E1A2E',
            ink2: '#8A2846',
            ink3: '#BE4D6C',
            ink4: '#D88095',
            red: '#DC2626',
            orange: '#EA580C',
            green: '#16A34A',
            blue: '#2563EB',
            purple: '#7C3AED',
            accent: '#E11D48',
        },
        dark: {
            bg: '#1C0A10',
            surface: '#2A1018',
            surface2: '#3D1524',
            border: '#4D1C30',
            border2: '#5E2540',
            ink: '#FFE0E5',
            ink2: '#FBBDC5',
            ink3: '#D4737F',
            ink4: '#A04A5A',
            red: '#F87171',
            orange: '#FB923C',
            green: '#4ADE80',
            blue: '#60A5FA',
            purple: '#A78BFA',
            accent: '#FB7185',
        },
    },
};

// Keep backward compat
export const colors = THEME_PRESETS.classic;

// Shadow presets — subtle, modern elevation
const shadows = {
    none: {
        shadowColor: 'transparent',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0,
        shadowRadius: 0,
        elevation: 0,
    },
    sm: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
        elevation: 1,
    },
    md: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    lg: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 16,
        elevation: 6,
    },
};

export const getTheme = (isDark, presetKey = 'classic') => {
    const preset = THEME_PRESETS[presetKey] || THEME_PRESETS.classic;
    return {
        colors: isDark ? preset.dark : preset.light,
        fonts: {
            // Geist — matches the Claude Design exactly
            d: 'Geist-Bold',
            m: 'Geist',
            s: 'Geist-SemiBold',
            b: 'Geist-Bold',
            mono: 'DMMono',
            // Logo uses display serif; Fraunces would be a closer match to design
            // but PlayfairDisplay is already bundled and reads similarly.
            logo: 'PlayfairDisplay-Bold',
        },
        shadows,
        radii: { r: 10, lg: 14, xl: 20, round: 9999 },
    };
};

export const theme = getTheme(false);
